[[main]]
  name = "VEREIN «OBERIG»"
  pageRef = "about"
  weight = 10

[[main]]
  name = "SAMSTAGSSCHULE"
  pageRef = "school"
  weight = 20

[[main]]
  name = "PROJEKTE"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "NACHRICHTEN"
  pageRef = "news"
  weight = 40

[[main]]
  name = "Kontakt"
  pageRef = "contacts"
  weight = 50

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://www.instagram.com/oberig.de"
  weight = 200

[[footer]]
  name = "IMPRESSUM | DATENSCHUTZ"
  pageRef = "privacy"
  weight = 10