backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dqzyy5upv
    api_key: 963455817932761

media_folder: static/img
public_folder: /img

collections:

  - name: 'pages_uk'
    label: 'Сторінки (українська)'
    files:

      - name: 'home_uk'
        label: 'ГОЛОВНА УКРАЇНСЬКА'
        file: 'content/_index.uk.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', hint: 'Введіть заголовок сторінки.' }
          - { label: 'Description', name: 'description', widget: 'string', hint: 'Короткий опис вмісту сторінки, який буде показаний у результатах пошуку, наприклад, в Google.' }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Напишіть основний текст сторінки у форматі Markdown.' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }

      - name: 'about_uk'
        label: 'ТОВАРИСТВО «ОБЕРІГ»'
        file: 'content/about/index.uk.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', hint: 'Введіть заголовок сторінки.' }
          - { label: 'Description', name: 'description', widget: 'string', hint: 'Короткий опис вмісту сторінки.' }
          - { label: 'Featured Image', name: 'featured', widget: 'image', required: false, hint: 'Оберіть зображення, яке буде основним та відображатиметься на початку сторінки.' }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Напишіть основний текст сторінки у форматі Markdown.' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }

      - name: 'school_uk'
        label: 'СУБОТНЯ ШКОЛА'
        file: 'content/school/index.uk.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', hint: 'Введіть заголовок сторінки.' }
          - { label: 'Description', name: 'description', widget: 'string', hint: 'Короткий опис вмісту сторінки.' }
          - { label: 'Featured Image', name: 'featured', widget: 'image', required: false, hint: 'Оберіть зображення, яке буде основним та відображатиметься на початку сторінки.' }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Напишіть основний текст сторінки у форматі Markdown.' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }

      - name: 'contacts_uk'
        label: 'Контакти'
        file: 'content/contacts/index.uk.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', hint: 'Введіть заголовок сторінки.' }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Напишіть основний текст сторінки у форматі Markdown.' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }


  - name: 'pages_de'
    label: 'Сторінки (німецька)'
    files:

      - name: 'home_de'
        label: 'ГОЛОВНА НІМЕЦЬКА'
        file: 'content/_index.de.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', hint: 'Введіть заголовок сторінки.' }
          - { label: 'Description', name: 'description', widget: 'string', hint: 'Короткий опис вмісту сторінки, який буде показаний у результатах пошуку, наприклад, в Google.' }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Напишіть основний текст сторінки у форматі Markdown.' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'de' }

      - name: 'about_de'
        label: 'VEREIN «OBERIG»'
        file: 'content/about/index.de.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', hint: 'Введіть заголовок сторінки.' }
          - { label: 'Description', name: 'description', widget: 'string', hint: 'Короткий опис вмісту сторінки.' }
          - { label: 'Featured Image', name: 'featured', widget: 'image', required: false, hint: 'Оберіть зображення, яке буде основним та відображатиметься на початку сторінки.' }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Напишіть основний текст сторінки у форматі Markdown.' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'de' }

      - name: 'school_de'
        label: 'SAMSTAGSSCHULE'
        file: 'content/school/index.de.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', hint: 'Введіть заголовок сторінки.' }
          - { label: 'Description', name: 'description', widget: 'string', hint: 'Короткий опис вмісту сторінки.' }
          - { label: 'Featured Image', name: 'featured', widget: 'image', required: false, hint: 'Оберіть зображення, яке буде основним та відображатиметься на початку сторінки.' }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Напишіть основний текст сторінки у форматі Markdown.' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'de' }

      - name: 'contacts_de'
        label: 'Kontakt'
        file: 'content/contacts/index.de.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', hint: 'Введіть заголовок сторінки.' }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Напишіть основний текст сторінки у форматі Markdown.' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'de' }


  - name: 'projects'
    label: 'Проєкти (укр./нім.)'
    folder: 'content/projects'
    create: true
    filter:
      field: 'type'
      value: 'post'
    fields:
      - { label: 'Language', name: 'language', widget: 'select', options: ['uk', 'de'], hint: 'Виберіть мову для цієї сторінки.' }
      - { label: 'Title', name: 'title', widget: 'string', hint: 'Введіть заголовок сторінки.' }
      - { label: 'Slug', name: 'slug', widget: 'string', hint: 'Введіть URL-частину для сторінки. Використовуйте латинські маленькі літери та дефіси між словами.' }
      - { label: 'Description', name: 'description', widget: 'string', hint: 'Короткий опис вмісту сторінки.' }
      - { label: 'Featured Image', name: 'featured', widget: 'image', required: false, hint: 'Оберіть зображення, яке буде основним та відображатиметься на початку сторінки.' }
      - { label: 'Publish Date', name: 'publish_date', widget: 'datetime', required: false, hint: 'Виберіть дату публікації сторінки.' }
      - { label: 'Weight', name: 'weight', widget: 'number', hint: 'Визначте вагу елемента для сортування. Чим менше значення, тим вище позиція сторінки. Якщо вагу не задано, сторінки будуть сортуватися за датою.' }
      - { label: 'Tags', name: 'tags', widget: 'list', hint: 'Додайте теги для кращого пошуку та категоризації.' }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Напишіть основний текст сторінки у форматі Markdown.' }


  - name: 'news'
    label: 'Новини (укр./нім.)'
    folder: 'content/news'
    create: true
    filter:
      field: 'type'
      value: 'post'
    fields:
      - { label: 'Language', name: 'language', widget: 'select', options: ['uk', 'de'], hint: 'Виберіть мову для цієї сторінки.' }
      - { label: 'Title', name: 'title', widget: 'string', hint: 'Введіть заголовок сторінки.' }
      - { label: 'Slug', name: 'slug', widget: 'string', hint: 'Введіть URL-частину для сторінки. Використовуйте латинські маленькі літери та дефіси між словами.' }
      - { label: 'Description', name: 'description', widget: 'string', hint: 'Короткий опис вмісту сторінки.' }
      - { label: 'Featured Image', name: 'featured', widget: 'image', required: false, hint: 'Оберіть зображення, яке буде основним та відображатиметься на початку сторінки.' }
      - { label: 'Publish Date', name: 'publish_date', widget: 'datetime', hint: 'Виберіть дату публікації сторінки.' }
      - { label: 'Weight', name: 'weight', widget: 'number', hint: 'Визначте вагу елемента для сортування. Чим менше значення, тим вище позиція сторінки. Якщо вагу не задано, сторінки будуть сортуватися за датою.' }
      - { label: 'Tags', name: 'tags', widget: 'list', hint: 'Додайте теги для кращого пошуку та категоризації.' }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Напишіть основний текст сторінки у форматі Markdown.' }
