local_backend: false

backend:
  name: git-gateway
  branch: main

media_folder: static/media
public_folder: /media

# display_url: https://localhost:1313
# site_url: https://localhost:1313

media_library:
  name: cloudinary
  config:
    cloud_name: dqzyy5upv
    api_key: 963455817932761

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

i18n:
  locales: [uk, de]
  structure: multiple_files
  default_locale: uk

collections:
  - name: 'home'
    label: 'Головна'
    folder: 'content'
    i18n: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true, hint: 'Заголовок головної сторінки. Використовується в результатах пошуку Google.' }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true, required: false, hint: 'Короткий опис для головної сторінки. Відображається у результатах пошуку Google.' }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true, required: false }

  - name: 'about'
    label: 'Про нас'
    folder: 'content/about'
    i18n: true
    fields:
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, i18n: true , hint: 'Увімкніть, якщо проєкт ще не готовий для публікації.' }
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Featured Image', name: 'featureimage', widget: 'image', required: false, i18n: duplicate }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'Show Date', name: 'showdate', widget: 'hidden', default: false, i18n: duplicate }

  - name: 'school'
    label: 'Школа'
    folder: 'content/school'
    i18n: true
    fields:
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, i18n: true , hint: 'Увімкніть, якщо проєкт ще не готовий для публікації.' }
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Featured Image', name: 'featureimage', widget: 'image', required: false, i18n: duplicate }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'Show Date', name: 'showdate', widget: 'hidden', default: false, i18n: duplicate }

  - name: 'projects'
    label: 'Проєкти'
    folder: 'content/projects'
    create: true
    filter: {field: 'visibleInCMS', value: true}
    slug: '{{fields.slug}}'
    i18n: true
    fields:
      - label: Draft
        name: draft
        widget: boolean
        default: false
        i18n: true
        hint: 'Увімкніть, якщо проєкт ще не готовий для публікації.'
      - lable: Slug
        name: slug
        widget: string
        i18n: duplicate
        pattern: ['^[a-z0-9-]{3,}$', "Має містити лише латинські малі літери, цифри та дефіси, і бути щонайменше 3 символи."]
        hint: "Введіть назву файлу, використовуючи  лише латинські малі літери, цифри та дефіси, і бути щонайменше 3 символи."
      - label: Title
        name: title
        widget: string
        i18n: true
        hint: 'Введіть заголовок сторінки.'
      - label: Description
        name: description
        widget: string
        required: false
        i18n: true
        hint: 'Короткий опис вмісту сторінки.'
      - label: Weight
        name: weight
        widget: number
        i18n: duplicate
        required: false
        hint: 'Визначте вагу елемента для сортування. Чим менше значення, тим вище позиція сторінки. Якщо вагу не задано, сторінки будуть сортуватися за датою.'
      - label: Featured Image
        name: featureimage
        widget: image
        i18n: duplicate
        required: false
        hint: 'Оберіть зображення, яке буде основним та відображатиметься на початку сторінки.'
      - label: Body
        name: body
        widget: markdown
        i18n: true
        hint: 'Напишіть основний текст сторінки у форматі Markdown.'
      - label: Visible in CMS
        name: visibleInCMS
        widget: hidden
        i18n: duplicate
        default: true

  - name: 'news'
    label: 'Новини'
    folder: 'content/news'
    slug: '{{fields.slug}}'
    create: true
    filter: {field: 'visibleInCMS', value: true}
    i18n: true
    fields:
      - label: Draft
        name: draft
        widget: boolean
        default: false
        i18n: true
        hint: 'Увімкніть, якщо проєкт ще не готовий для публікації.'
      - label: Title
        name: title
        widget: string
        i18n: true
        hint: "Введіть заголовок сторінки."
      - lable: Slug
        name: slug
        widget: string
        i18n: duplicate
        pattern: ['^[a-z0-9-]{3,}$', "Має містити лише латинські малі літери, цифри та дефіси, і бути щонайменше 3 символи."]
        hint: "Введіть назву файлу, використовуючи  лише латинські малі літери, цифри та дефіси, і бути щонайменше 3 символи."
      - label: Description
        name: description
        widget: string
        required: false
        i18n: true
        hint: "Короткий опис вмісту сторінки."
      - label: Featured Image
        name: featureimage
        widget: image
        i18n: duplicate
        required: false
        hint: "Оберіть зображення, яке буде основним та відображатиметься на початку сторінки."
      - label: Publish Date
        name: publish_date
        widget: datetime
        i18n: duplicate
        hint: "Виберіть дату публікації сторінки."
      - label: Body
        name: body
        widget: markdown
        i18n: true
        hint: "Напишіть основний текст сторінки у форматі Markdown."
      - label: Visible in CMS
        name: visibleInCMS
        widget: hidden
        i18n: duplicate
        default: true

  - name: 'contacts'
    label: 'Контакти'
    folder: 'content/contacts'
    i18n: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }

  - name: 'privacy_notice'
    label: 'Політика конфіденційності'
    folder: 'content/privacy'
    i18n: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
