backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dqzyy5upv
    api_key: 963455817932761

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages_de'
    label: 'Pages (German)'
    files:
      - name: 'home_de'
        label: 'Home (DE)'
        file: 'content/_index.de.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'de' }
      
      - name: 'about_de'
        label: 'About (DE)'
        file: 'content/about/index.de.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Featured Image', name: 'featured', widget: 'image', required: false }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'de' }

      - name: 'contacts_de'
        label: 'Contacts (DE)'
        file: 'content/contacts/index.de.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'de' }

      - name: 'school_de'
        label: 'School (DE)'
        file: 'content/school/index.de.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'de' }

  - name: 'pages_uk'
    label: 'Pages (Ukrainian)'
    files:
      - name: 'home_uk'
        label: 'Home (UK)'
        file: 'content/_index.uk.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
      
      - name: 'about_uk'
        label: 'About (UK)'
        file: 'content/about/index.uk.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Featured Image', name: 'featured', widget: 'image', required: false }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }

      - name: 'contacts_uk'
        label: 'Contacts (UK)'
        file: 'content/contacts/index.uk.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }

      - name: 'school_uk'
        label: 'School (UK)'
        file: 'content/school/index.uk.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }

  - name: 'news'
    label: 'News'
    folder: 'content/news'
    create: true
    nested:
      depth: 2
      summary: '{{title}}'
    filter:
      field: 'type'
      value: 'post'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'featured', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Language', name: 'language', widget: 'select', options: ['de', 'uk'] }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'post' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }

  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    create: true
    nested:
      depth: 2
      summary: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'featured', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Language', name: 'language', widget: 'select', options: ['de', 'uk'] }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }

  - name: 'section_indices_de'
    label: 'Section Pages (German)'
    files:
      - name: 'news_index_de'
        label: 'News Overview (DE)'
        file: 'content/news/_index.de.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'de' }
      
      - name: 'projects_index_de'
        label: 'Projects Overview (DE)'
        file: 'content/projects/_index.de.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'de' }

  - name: 'section_indices_uk'
    label: 'Section Pages (Ukrainian)'
    files:
      - name: 'news_index_uk'
        label: 'News Overview (UK)'
        file: 'content/news/_index.uk.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }
      
      - name: 'projects_index_uk'
        label: 'Projects Overview (UK)'
        file: 'content/projects/_index.uk.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Language', name: 'language', widget: 'hidden', default: 'uk' }